services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: rail
      POSTGRES_PASSWORD: 1234
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: